/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretariasRouteImport } from './routes/secretarias'
import { Route as ProcessosRouteImport } from './routes/processos'
import { Route as NumeracaoRouteImport } from './routes/numeracao'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IrpRouteImport } from './routes/irp'
import { Route as ImportarContratosRouteImport } from './routes/importar-contratos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as GestoresRouteImport } from './routes/gestores'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FiscaisRouteImport } from './routes/fiscais'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcessosIdRouteImport } from './routes/processos.$id'
import { Route as ContratosIdRouteImport } from './routes/contratos.$id'

const SecretariasRoute = SecretariasRouteImport.update({
  id: '/secretarias',
  path: '/secretarias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const NumeracaoRoute = NumeracaoRouteImport.update({
  id: '/numeracao',
  path: '/numeracao',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IrpRoute = IrpRouteImport.update({
  id: '/irp',
  path: '/irp',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarContratosRoute = ImportarContratosRouteImport.update({
  id: '/importar-contratos',
  path: '/importar-contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const GestoresRoute = GestoresRouteImport.update({
  id: '/gestores',
  path: '/gestores',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscaisRoute = FiscaisRouteImport.update({
  id: '/fiscais',
  path: '/fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosIdRoute = ProcessosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProcessosRoute,
} as any)
const ContratosIdRoute = ContratosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContratosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fiscais': typeof FiscaisRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestores': typeof GestoresRoute
  '/historico': typeof HistoricoRoute
  '/importar-contratos': typeof ImportarContratosRoute
  '/irp': typeof IrpRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/numeracao': typeof NumeracaoRoute
  '/processos': typeof ProcessosRouteWithChildren
  '/secretarias': typeof SecretariasRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/processos/$id': typeof ProcessosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fiscais': typeof FiscaisRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestores': typeof GestoresRoute
  '/historico': typeof HistoricoRoute
  '/importar-contratos': typeof ImportarContratosRoute
  '/irp': typeof IrpRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/numeracao': typeof NumeracaoRoute
  '/processos': typeof ProcessosRouteWithChildren
  '/secretarias': typeof SecretariasRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/processos/$id': typeof ProcessosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fiscais': typeof FiscaisRoute
  '/fornecedores': typeof FornecedoresRoute
  '/gestores': typeof GestoresRoute
  '/historico': typeof HistoricoRoute
  '/importar-contratos': typeof ImportarContratosRoute
  '/irp': typeof IrpRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/numeracao': typeof NumeracaoRoute
  '/processos': typeof ProcessosRouteWithChildren
  '/secretarias': typeof SecretariasRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/processos/$id': typeof ProcessosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contratos'
    | '/dashboard'
    | '/fiscais'
    | '/fornecedores'
    | '/gestores'
    | '/historico'
    | '/importar-contratos'
    | '/irp'
    | '/login'
    | '/logs'
    | '/numeracao'
    | '/processos'
    | '/secretarias'
    | '/contratos/$id'
    | '/processos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contratos'
    | '/dashboard'
    | '/fiscais'
    | '/fornecedores'
    | '/gestores'
    | '/historico'
    | '/importar-contratos'
    | '/irp'
    | '/login'
    | '/logs'
    | '/numeracao'
    | '/processos'
    | '/secretarias'
    | '/contratos/$id'
    | '/processos/$id'
  id:
    | '__root__'
    | '/'
    | '/contratos'
    | '/dashboard'
    | '/fiscais'
    | '/fornecedores'
    | '/gestores'
    | '/historico'
    | '/importar-contratos'
    | '/irp'
    | '/login'
    | '/logs'
    | '/numeracao'
    | '/processos'
    | '/secretarias'
    | '/contratos/$id'
    | '/processos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContratosRoute: typeof ContratosRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FiscaisRoute: typeof FiscaisRoute
  FornecedoresRoute: typeof FornecedoresRoute
  GestoresRoute: typeof GestoresRoute
  HistoricoRoute: typeof HistoricoRoute
  ImportarContratosRoute: typeof ImportarContratosRoute
  IrpRoute: typeof IrpRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  NumeracaoRoute: typeof NumeracaoRoute
  ProcessosRoute: typeof ProcessosRouteWithChildren
  SecretariasRoute: typeof SecretariasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretarias': {
      id: '/secretarias'
      path: '/secretarias'
      fullPath: '/secretarias'
      preLoaderRoute: typeof SecretariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeracao': {
      id: '/numeracao'
      path: '/numeracao'
      fullPath: '/numeracao'
      preLoaderRoute: typeof NumeracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irp': {
      id: '/irp'
      path: '/irp'
      fullPath: '/irp'
      preLoaderRoute: typeof IrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-contratos': {
      id: '/importar-contratos'
      path: '/importar-contratos'
      fullPath: '/importar-contratos'
      preLoaderRoute: typeof ImportarContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestores': {
      id: '/gestores'
      path: '/gestores'
      fullPath: '/gestores'
      preLoaderRoute: typeof GestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscais': {
      id: '/fiscais'
      path: '/fiscais'
      fullPath: '/fiscais'
      preLoaderRoute: typeof FiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos/$id': {
      id: '/processos/$id'
      path: '/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof ProcessosIdRouteImport
      parentRoute: typeof ProcessosRoute
    }
    '/contratos/$id': {
      id: '/contratos/$id'
      path: '/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof ContratosIdRouteImport
      parentRoute: typeof ContratosRoute
    }
  }
}

interface ContratosRouteChildren {
  ContratosIdRoute: typeof ContratosIdRoute
}

const ContratosRouteChildren: ContratosRouteChildren = {
  ContratosIdRoute: ContratosIdRoute,
}

const ContratosRouteWithChildren = ContratosRoute._addFileChildren(
  ContratosRouteChildren,
)

interface ProcessosRouteChildren {
  ProcessosIdRoute: typeof ProcessosIdRoute
}

const ProcessosRouteChildren: ProcessosRouteChildren = {
  ProcessosIdRoute: ProcessosIdRoute,
}

const ProcessosRouteWithChildren = ProcessosRoute._addFileChildren(
  ProcessosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContratosRoute: ContratosRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FiscaisRoute: FiscaisRoute,
  FornecedoresRoute: FornecedoresRoute,
  GestoresRoute: GestoresRoute,
  HistoricoRoute: HistoricoRoute,
  ImportarContratosRoute: ImportarContratosRoute,
  IrpRoute: IrpRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  NumeracaoRoute: NumeracaoRoute,
  ProcessosRoute: ProcessosRouteWithChildren,
  SecretariasRoute: SecretariasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
