/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSecretariasRouteImport } from './routes/_authenticated.secretarias'
import { Route as AuthenticatedProcessosRouteImport } from './routes/_authenticated.processos'
import { Route as AuthenticatedNumeracaoRouteImport } from './routes/_authenticated.numeracao'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated.logs'
import { Route as AuthenticatedIrpColunasRouteImport } from './routes/_authenticated.irp-colunas'
import { Route as AuthenticatedIrpRouteImport } from './routes/_authenticated.irp'
import { Route as AuthenticatedImportarContratosRouteImport } from './routes/_authenticated.importar-contratos'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated.historico'
import { Route as AuthenticatedGestoresRouteImport } from './routes/_authenticated.gestores'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated.fornecedores'
import { Route as AuthenticatedFiscaisRouteImport } from './routes/_authenticated.fiscais'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated.contratos'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated.processos.$id'
import { Route as AuthenticatedContratosIdRouteImport } from './routes/_authenticated.contratos.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSecretariasRoute =
  AuthenticatedSecretariasRouteImport.update({
    id: '/_authenticated/secretarias',
    path: '/secretarias',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProcessosRoute = AuthenticatedProcessosRouteImport.update({
  id: '/_authenticated/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNumeracaoRoute = AuthenticatedNumeracaoRouteImport.update({
  id: '/_authenticated/numeracao',
  path: '/numeracao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/_authenticated/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIrpColunasRoute = AuthenticatedIrpColunasRouteImport.update({
  id: '/_authenticated/irp-colunas',
  path: '/irp-colunas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIrpRoute = AuthenticatedIrpRouteImport.update({
  id: '/_authenticated/irp',
  path: '/irp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedImportarContratosRoute =
  AuthenticatedImportarContratosRouteImport.update({
    id: '/_authenticated/importar-contratos',
    path: '/importar-contratos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/_authenticated/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGestoresRoute = AuthenticatedGestoresRouteImport.update({
  id: '/_authenticated/gestores',
  path: '/gestores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/_authenticated/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFiscaisRoute = AuthenticatedFiscaisRouteImport.update({
  id: '/_authenticated/fiscais',
  path: '/fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/_authenticated/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProcessosRoute,
  } as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fiscais': typeof AuthenticatedFiscaisRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/gestores': typeof AuthenticatedGestoresRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importar-contratos': typeof AuthenticatedImportarContratosRoute
  '/irp': typeof AuthenticatedIrpRoute
  '/irp-colunas': typeof AuthenticatedIrpColunasRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/numeracao': typeof AuthenticatedNumeracaoRoute
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/secretarias': typeof AuthenticatedSecretariasRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fiscais': typeof AuthenticatedFiscaisRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/gestores': typeof AuthenticatedGestoresRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importar-contratos': typeof AuthenticatedImportarContratosRoute
  '/irp': typeof AuthenticatedIrpRoute
  '/irp-colunas': typeof AuthenticatedIrpColunasRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/numeracao': typeof AuthenticatedNumeracaoRoute
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/secretarias': typeof AuthenticatedSecretariasRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fiscais': typeof AuthenticatedFiscaisRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/gestores': typeof AuthenticatedGestoresRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/importar-contratos': typeof AuthenticatedImportarContratosRoute
  '/_authenticated/irp': typeof AuthenticatedIrpRoute
  '/_authenticated/irp-colunas': typeof AuthenticatedIrpColunasRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/numeracao': typeof AuthenticatedNumeracaoRoute
  '/_authenticated/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/_authenticated/secretarias': typeof AuthenticatedSecretariasRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/contratos'
    | '/dashboard'
    | '/fiscais'
    | '/fornecedores'
    | '/gestores'
    | '/historico'
    | '/importar-contratos'
    | '/irp'
    | '/irp-colunas'
    | '/logs'
    | '/numeracao'
    | '/processos'
    | '/secretarias'
    | '/contratos/$id'
    | '/processos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/contratos'
    | '/dashboard'
    | '/fiscais'
    | '/fornecedores'
    | '/gestores'
    | '/historico'
    | '/importar-contratos'
    | '/irp'
    | '/irp-colunas'
    | '/logs'
    | '/numeracao'
    | '/processos'
    | '/secretarias'
    | '/contratos/$id'
    | '/processos/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reset-password'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/fiscais'
    | '/_authenticated/fornecedores'
    | '/_authenticated/gestores'
    | '/_authenticated/historico'
    | '/_authenticated/importar-contratos'
    | '/_authenticated/irp'
    | '/_authenticated/irp-colunas'
    | '/_authenticated/logs'
    | '/_authenticated/numeracao'
    | '/_authenticated/processos'
    | '/_authenticated/secretarias'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/processos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFiscaisRoute: typeof AuthenticatedFiscaisRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedGestoresRoute: typeof AuthenticatedGestoresRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedImportarContratosRoute: typeof AuthenticatedImportarContratosRoute
  AuthenticatedIrpRoute: typeof AuthenticatedIrpRoute
  AuthenticatedIrpColunasRoute: typeof AuthenticatedIrpColunasRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedNumeracaoRoute: typeof AuthenticatedNumeracaoRoute
  AuthenticatedProcessosRoute: typeof AuthenticatedProcessosRouteWithChildren
  AuthenticatedSecretariasRoute: typeof AuthenticatedSecretariasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/secretarias': {
      id: '/_authenticated/secretarias'
      path: '/secretarias'
      fullPath: '/secretarias'
      preLoaderRoute: typeof AuthenticatedSecretariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/processos': {
      id: '/_authenticated/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof AuthenticatedProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/numeracao': {
      id: '/_authenticated/numeracao'
      path: '/numeracao'
      fullPath: '/numeracao'
      preLoaderRoute: typeof AuthenticatedNumeracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/irp-colunas': {
      id: '/_authenticated/irp-colunas'
      path: '/irp-colunas'
      fullPath: '/irp-colunas'
      preLoaderRoute: typeof AuthenticatedIrpColunasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/irp': {
      id: '/_authenticated/irp'
      path: '/irp'
      fullPath: '/irp'
      preLoaderRoute: typeof AuthenticatedIrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/importar-contratos': {
      id: '/_authenticated/importar-contratos'
      path: '/importar-contratos'
      fullPath: '/importar-contratos'
      preLoaderRoute: typeof AuthenticatedImportarContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestores': {
      id: '/_authenticated/gestores'
      path: '/gestores'
      fullPath: '/gestores'
      preLoaderRoute: typeof AuthenticatedGestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fiscais': {
      id: '/_authenticated/fiscais'
      path: '/fiscais'
      fullPath: '/fiscais'
      preLoaderRoute: typeof AuthenticatedFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedProcessosRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
  }
}

interface AuthenticatedContratosRouteChildren {
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRoute
}

const AuthenticatedContratosRouteChildren: AuthenticatedContratosRouteChildren =
  {
    AuthenticatedContratosIdRoute: AuthenticatedContratosIdRoute,
  }

const AuthenticatedContratosRouteWithChildren =
  AuthenticatedContratosRoute._addFileChildren(
    AuthenticatedContratosRouteChildren,
  )

interface AuthenticatedProcessosRouteChildren {
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
}

const AuthenticatedProcessosRouteChildren: AuthenticatedProcessosRouteChildren =
  {
    AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
  }

const AuthenticatedProcessosRouteWithChildren =
  AuthenticatedProcessosRoute._addFileChildren(
    AuthenticatedProcessosRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFiscaisRoute: AuthenticatedFiscaisRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedGestoresRoute: AuthenticatedGestoresRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedImportarContratosRoute: AuthenticatedImportarContratosRoute,
  AuthenticatedIrpRoute: AuthenticatedIrpRoute,
  AuthenticatedIrpColunasRoute: AuthenticatedIrpColunasRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedNumeracaoRoute: AuthenticatedNumeracaoRoute,
  AuthenticatedProcessosRoute: AuthenticatedProcessosRouteWithChildren,
  AuthenticatedSecretariasRoute: AuthenticatedSecretariasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
